### ISSUE TITLE
differences in docs regarding invocation

### ISSUE THREAD

**Issue by marrip** [InPreD/TSOPPI_SADET#3]
Checking https://tsoppi.readthedocs.io/en/latest/SADET.html it says that the tool is called via `extract_IMPRESS_sample_data.py` when calling it directly and via docker it is `/inpred/SADET.py`. Is the former one that "old name" maybe or is there actually different scripts that are called?

**Comment by danielvo** [comment]
Good catch there! That was indeed the old name. I have corrected that now. Many thanks!
